import {Chess} from 'chess.js';
import type {Member} from './lobby.ts';
export type ArcadeMode='dominoes'|'chess';
export type Domino={id:string,a:number,b:number};
export type ArcadeAction={type:'domino',tile:string,end:'left'|'right'}|{type:'pass'}|{type:'next'}|{type:'chess',from:string,to:string,promotion?:string}|{type:'resign'};
export type ArcadeRoom={id:string,mode:ArcadeMode,seats:Member[],status:'waiting'|'playing'|'roundEnd'|'finished',version:number,created:number,updated:number,waitUntil:number,lastBot:number,deadline:number,turn:number,round:number,starter:number,scores:[number,number],winner:number|null,reason:string,abandoned:string[],domino?:{hands:Domino[][],chain:Domino[],passes:number},chess?:{moves:string[],fen:string}};
function ensure(value:unknown,message:string):asserts value{if(!value)throw Error(message)}
export const arcadeFor=(rooms:ArcadeRoom[],id:string)=>rooms.find(r=>r.seats.some(p=>p.id===id));
export function makeArcade(mode:ArcadeMode,player:Member,id:string,now:number):ArcadeRoom{return{id,mode,seats:[{...player,ready:true}],status:'waiting',version:0,created:now,updated:now,waitUntil:now+20000,lastBot:now,deadline:now+120000,turn:0,round:1,starter:0,scores:[0,0],winner:null,reason:'',abandoned:[]}}
function shuffle<T>(a:T[]){for(let i=a.length-1;i>0;i--){const range=i+1,limit=Math.floor(4294967296/range)*range;let n:number;do{n=crypto.getRandomValues(new Uint32Array(1))[0]}while(n>=limit);const j=n%range;[a[i],a[j]]=[a[j],a[i]]}return a}
function dealDomino(r:ArcadeRoom){const tiles=shuffle(Array.from({length:7},(_,a)=>Array.from({length:7-a},(_,i)=>({id:`${a}-${a+i}`,a,b:a+i}))).flat());const hands=Array.from({length:4},(_,i)=>tiles.slice(i*7,i*7+7));if(r.round===1)r.starter=hands.findIndex(h=>h.some(t=>t.a===6&&t.b===6));r.turn=r.starter;r.domino={hands,chain:[],passes:0};r.reason='';r.winner=null;r.status='playing'}
export function startArcade(r:ArcadeRoom,now:number){ensure(r.status==='waiting','This game already started.');const count=r.mode==='chess'?2:4;while(r.seats.length<count){const n=r.seats.length;r.seats.push({id:`${r.id}:bot:${n}`,name:['Dara','Roj','Ari'][n-1]||'Bot',tag:'BOT',ready:true,bot:true})}r.status='playing';if(r.mode==='dominoes')dealDomino(r);else r.chess={moves:[],fen:new Chess().fen()};r.version++;r.lastBot=now;r.deadline=now+120000;r.updated=now}
export function dominoChoices(r:ArcadeRoom,seat:number){if(!r.domino||r.status!=='playing'||r.turn!==seat)return[];const d=r.domino,left=d.chain[0]?.a,right=d.chain.at(-1)?.b;return d.hands[seat].flatMap(tile=>{if(!d.chain.length)return r.round===1&&!(tile.a===6&&tile.b===6)?[]:[{type:'domino' as const,tile:tile.id,end:'right' as const}];const result:Extract<ArcadeAction,{type:'domino'}>[]=[];if(tile.a===left||tile.b===left)result.push({type:'domino',tile:tile.id,end:'left'});if(tile.a===right||tile.b===right)result.push({type:'domino',tile:tile.id,end:'right'});return result})}
export function chessPosition(r:ArcadeRoom){const c=new Chess();for(const move of r.chess?.moves||[])c.move(move);return c}
const sum=(h:Domino[])=>h.reduce((n,t)=>n+t.a+t.b,0);
function endDomino(r:ArcadeRoom,winner:number|null){const d=r.domino!;r.winner=winner;if(winner!==null){const losing=1-winner%2;r.scores[winner%2]+=sum(d.hands[losing])+sum(d.hands[losing+2])}r.status=Math.max(...r.scores)>=100?'finished':'roundEnd';r.reason=winner===null?'draw':d.passes===4?'blocked':'empty'}
export function applyArcade(input:ArcadeRoom,seat:number,a:ArcadeAction,now:number):ArcadeRoom{
 const r=structuredClone(input);ensure(seat>=0&&seat<r.seats.length,'Not seated here.');
 if(a.type==='resign'){ensure(r.status==='playing'||r.status==='roundEnd','The game is not active.');if(r.mode==='chess'){r.status='finished';r.winner=1-seat;r.scores[r.winner]=1;r.reason='resigned';r.abandoned.push(r.seats[seat].id)}else{r.abandoned.push(r.seats[seat].id);r.seats[seat].bot=true}}else if(a.type==='next'){ensure(r.mode==='dominoes'&&r.status==='roundEnd','The round is not over.');r.round++;r.starter=(r.starter+1)%4;dealDomino(r)}else{
 ensure(r.status==='playing'&&r.turn===seat,'Not your turn.');
 if(r.mode==='dominoes'){
  const d=r.domino!,choices=dominoChoices(r,seat);
  if(a.type==='pass'){ensure(choices.length===0,'You have a playable tile.');d.passes++;if(d.passes===4){const a=sum(d.hands[0])+sum(d.hands[2]),b=sum(d.hands[1])+sum(d.hands[3]);endDomino(r,a===b?null:a<b?0:1)}}
  else{ensure(a.type==='domino'&&choices.some(c=>c.tile===a.tile&&c.end===a.end),'That tile does not match.');const tile=d.hands[seat].find(t=>t.id===a.tile)!;d.hands[seat]=d.hands[seat].filter(t=>t.id!==tile.id);let piece={...tile};if(d.chain.length){if(a.end==='left'&&piece.b!==d.chain[0].a||a.end==='right'&&piece.a!==d.chain.at(-1)!.b)piece={...piece,a:piece.b,b:piece.a}}if(a.end==='left')d.chain.unshift(piece);else d.chain.push(piece);d.passes=0;if(!d.hands[seat].length)endDomino(r,seat)}
  if(r.status==='playing')r.turn=(seat+1)%4;
 }else{ensure(a.type==='chess','Choose a chess move.');const c=chessPosition(r);const move=c.move({from:a.from,to:a.to,promotion:a.promotion||'q'});ensure(move,'Illegal chess move.');r.chess!.moves.push(move.san);r.chess!.fen=c.fen();r.turn=c.turn()==='w'?0:1;if(c.isCheckmate()){r.status='finished';r.winner=seat;r.scores[seat]=1;r.reason='checkmate'}else if(c.isDraw()||r.chess!.moves.length>=500){r.status='finished';r.winner=null;r.reason='draw'}else r.reason=c.isCheck()?'check':''}
 }
 r.version++;r.updated=now;r.deadline=now+120000;r.lastBot=now;return r;
}
export function arcadeBot(r:ArcadeRoom):ArcadeAction{
 if(r.mode==='dominoes'){const choices=dominoChoices(r,r.turn);choices.sort((a,b)=>{const hand=r.domino!.hands[r.turn];const x=hand.find(t=>t.id===a.tile)!,y=hand.find(t=>t.id===b.tile)!;return (y.a+y.b+(y.a===y.b?3:0))-(x.a+x.b+(x.a===x.b?3:0))});return choices[0]||{type:'pass'}}
 const c=chessPosition(r),values:Record<string,number>={p:1,n:3,b:3,r:5,q:9,k:100};let best=-Infinity,choice=c.moves({verbose:true})[0];for(const m of c.moves({verbose:true})){c.move(m);let score=(values[m.captured||'']||0)*10+(m.promotion?80:0)+(c.isCheck()?3:0)+(c.isCheckmate()?10000:0);if(c.isAttacked(m.to,c.turn()))score-=values[m.piece]*8;const file=m.to.charCodeAt(0)-97,rank=Number(m.to[1])-1;score+=(3.5-Math.abs(3.5-file))+(3.5-Math.abs(3.5-rank));c.undo();if(score>best){best=score;choice=m}}return{type:'chess',from:choice.from,to:choice.to,promotion:choice.promotion};
}
export function tickArcade(r:ArcadeRoom,now:number){if(r.status==='waiting'&&(r.seats.length===(r.mode==='chess'?2:4)||now>=r.waitUntil)){startArcade(r,now);return r}if(r.status==='playing'&&(r.seats[r.turn].bot&&now-r.lastBot>=850||now>=r.deadline))return applyArcade(r,r.turn,arcadeBot(r),now);return r}
export function arcadeView(r:ArcadeRoom,id:string){const seat=r.seats.findIndex(p=>p.id===id);ensure(seat>=0,'Not seated here.');const {domino,...rest}=r;const c=r.mode==='chess'&&r.chess?chessPosition(r):null;return{...rest,seat,domino:domino?{chain:domino.chain,passes:domino.passes,hand:domino.hands[seat],counts:domino.hands.map(h=>h.length)}:null,legalDomino:dominoChoices(r,seat),legalChess:c&&seat===r.turn&&r.status==='playing'?c.moves({verbose:true}).map(m=>({from:m.from,to:m.to,promotion:m.promotion})):[],reward:r.status==='finished'&&!r.abandoned.includes(id)?r.winner!==null&&(r.mode==='chess'?r.winner===seat:r.winner%2===seat%2)?60:30:0}}
export type ArcadeView=ReturnType<typeof arcadeView>;
